### PR TITLE
feat: add complete metadata config example with xpaths

### PR DESCRIPTION
**Pull request by Kate-Lyndegaard**
ING-3963

### CODE REVIEW

**Comment by Kate-Lyndegaard** [comment]
@morch23mj How can I create a new line for the xpath values?

grafik

**Comment by morch23mj** [comment]
> @morch23mj How can I create a new line for the xpath values?
That's possible through `<br/>` elements. I have pushed a commit containing those.

**Review by morch23mj — COMMENTED** [review]
Do we need to update `DE` and `CS` documents too?

**Review by JohannaOtt — APPROVED** [review]
@Kate-Lyndegaard I think this list is very valuable. I just wonder if it could be a bit too much input for someone reading the documentation. Did you consider providing the list for download somewhere or the like and only link it from the documentation or put it on a separate page of the documentation so that advanced users can read it and less advances users are not overwhelmed?
Do we also need to add it to the German version?

**Review by stempler — APPROVED** [review]

**Comment by Kate-Lyndegaard** [comment]
> Do we need to update DE and CS documents too?

@morch23mj Yes, that would be good. 

>Did you consider providing the list for download somewhere or the like and only link it from the documentation or put it on a separate page of the documentation so that advanced users can read it and less advances users are not overwhelmed?

@JohannaOtt I simply updated the existing documentation. If we want to change it now to link to a document, that is fine with me. @morch23mj Where would I store such a document that I could then link to?

>Do we also need to add it to the German version?

We can link the document on the German page, or is something else needed?

**Comment by morch23mj** [comment]
@Kate-Lyndegaard @JohannaOtt I just checked and there is also the possibility of having a [collapsable section](https://stackoverflow.com/questions/60827828/docusaurus-v2-collapsible-section-in-markdown). Is that maybe easier? If so, I can try to work on it.

**Comment by Kate-Lyndegaard** [comment]
@morch23mj Oooh, I like the collapsable section. That would be great here.

**Comment by Kate-Lyndegaard** [comment]
@morch23mj Can this be merged, or should it wait for additional changes?

**Comment by morch23mj** [comment]
@Kate-Lyndegaard I think if it's not super urgent, first add the changes related to the collapsible section.

**Comment by Kate-Lyndegaard** [comment]
@morch23mj I tried to add the collapsible section, however I got the following:
grafik

**Comment by morch23mj** [comment]
@Kate-Lyndegaard At least from the image, I see that `</p>` have no opening tag, and if it does, it should do after the `<li>` tag. If it's alright with you, I can also take that over. :)

**Comment by Kate-Lyndegaard** [comment]
@morch23mj I tried to follow the directions in the link you posted. It would be great if this is a quick fix. I just don't like leaving large and useful PRs hanging around.

**Comment by morch23mj** [comment]
@Kate-Lyndegaard @JohannaOtt I've made the two sections collapsable, and documented how it'd done in the README.md file for future reference.

There are two example sections (both collapsable), one is minimal (the one used before) and the other one is very detailed. I thought it's a good idea to keep both? If the short one isn't needed anymore then it can be deleted before merging.

Added same for other locales: de/cs.

**Comment by JohannaOtt** [comment]
@morch23mj Only looked at the screenshot now. Is there an easy way to change the design of them to adapt it to our documentation. Otherwise, LGTM
@Kate-Lyndegaard We could consider creating a ticket to move all config examples etc to such sections so that the documentation parts get less long and users can look at them in case they want more detailed information.

**Comment by morch23mj** [comment]
@JohannaOtt Thanks for the feedback. :)

I have inspected what styles are applied there, and it seems it's the ones coming from our theme. In this case, it's `alert-info` that's applied which has this default blue. I have copied over a component from our docs next to it, which is an alert-info too, and the two match the same original style.

Yellow color is reserved for `warning` and red for `danger` (e.g. errors), and so on.

If you still see that we could improve something here, your input is welcome!

**Comment by Kate-Lyndegaard** [comment]
@morch23mj Thank you, @morch23mj !

**Pull request merged**
