### PR TITLE
fix: exchange images in Czech help

### PR DESCRIPTION
**Pull request by JohannaOtt**
Sevitech asked to exchange the images used

WGS-2053

### CODE REVIEW

**Review by stempler — APPROVED** [review]

**Comment by stempler** [comment]
@JohannaOtt Maybe you can remind them that they can create pull requests for the help themselves as well.

**Review by morch23mj — APPROVED** [review]

**Comment by JohannaOtt** [comment]
@morch23mj @stempler I just wanted to check whether the correct images display in the help now. But when searching the repository for the names of the files I cannot find them. I thought they would need to be used somewhere in the code if they are embedded in the help. How can I find out where these images are used so that I can check if the correct ones are displayed now?

**Comment by morch23mj** [comment]
@JohannaOtt I have taken a look, and yes they're used in the code and not in the docs. 

As of now, the code uses the English version for all those modified images which are visible on the site homepage. I'll try to make a quick fix for that to use the appropriate locale image, then I'll test them locally and push the fix.

**Comment by JohannaOtt** [comment]
@morch23mj Thank you for looking into it. Would that also explain why no images are displayed on the start page when being logged in and using the czech version?
grafik
Or is that an independent issue as it concerns the platform code and not the documentation?

**Comment by morch23mj** [comment]
@JohannaOtt exactly, it's an independant issue. But it already gives a hint about resolving it, I'd guess both slovak and czech languages do not have the images folder set for them.

Screenshot 2022-11-22 at 13 30 39

**Comment by morch23mj** [comment]
@JohannaOtt yes, sure

**Comment by JohannaOtt** [comment]
I created https://wetransform.atlassian.net/browse/ING-3663 for it.

**Pull request merged**
